application: amesh-forecast
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /frame\.gif
  static_files: static/frame.gif
  upload: static/frame\.gif

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)

- url: .*
  script: ameshforecast.app
